<mxfile host="app.diagrams.net" modified="2024-06-05T00:08:51.858Z" agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" version="24.4.8" etag="mTO7pdDVX6wZ4SL4-AH6" type="github">
  <diagram name="Página-1" id="2qYeLRH0CXjsBAegM3-H">
    <mxGraphModel>
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
